<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageOutputPath>..\..\..\nuget</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="lib\**" />
    <EmbeddedResource Remove="lib\**" />
    <None Remove="lib\**" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NuspecFile>Kanvas.Debug.nuspec</NuspecFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NuspecFile>Kanvas.nuspec</NuspecFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCnEncoder.Net" Version="2.2.1" />
    <PackageReference Include="Komponent" Version="2.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kanvas.Contract\Kanvas.Contract.csproj" />
  </ItemGroup>

</Project>