<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <BuildNuget>false</BuildNuget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(BuildNuget)'=='true'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageOutputPath>..\..\..\nuget</PackageOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NuspecFile>Kaligraphy.Debug.nuspec</NuspecFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NuspecFile>Kaligraphy.nuspec</NuspecFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RectangleBinPack.CSharp" Version="1.0.4" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
    <PackageReference Include="System.Drawing.Common" Version="5.0.3" />
  </ItemGroup>

  <ItemGroup Condition="'$(BuildNuget)'=='true'">
    <PackageReference Include="Komponent" Version="2.1.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kaligraphy.Contract\Kaligraphy.Contract.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(BuildNuget)'=='false'">
    <ProjectReference Include="..\Komponent\Komponent.csproj" />
  </ItemGroup>

</Project>