<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <BuildNuget>false</BuildNuget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(BuildNuget)'=='true'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageOutputPath>..\..\..\nuget</PackageOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NuspecFile>Komponent.Debug.nuspec</NuspecFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NuspecFile>Komponent.nuspec</NuspecFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Komponent.Contract\Komponent.Contract.csproj" />
  </ItemGroup>

</Project>