<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kaligraphy" Version="2.1.24" />
    <PackageReference Include="Kanvas" Version="2.1.26" />
    <PackageReference Include="Kompression" Version="2.1.9" />
    <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>

</Project>
