<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <BuildNuget>false</BuildNuget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(BuildNuget)'=='true'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageOutputPath>..\..\..\nuget</PackageOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NuspecFile>Kompression.Debug.nuspec</NuspecFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NuspecFile>Kompression.nuspec</NuspecFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EasyCompressor.LZMA" Version="2.1.0" />
    <PackageReference Include="K4os.Compression.LZ4.Streams" Version="1.3.8" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
  </ItemGroup>

  <ItemGroup Condition="'$(BuildNuget)'=='true'">
    <PackageReference Include="Komponent" Version="2.1.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kompression.Contract\Kompression.Contract.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(BuildNuget)'=='false'">
    <ProjectReference Include="..\Komponent\Komponent.csproj" />
  </ItemGroup>

</Project>