name: Kuriimu2 Cmd

on:
  push:
    branches:
      - imgui
    paths:
      - 'src/ui/Kuriimu2.Cmd/**'
      - 'plugins/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - uses: nuget/setup-nuget@v2
    
    - name: Wait for other dev builds
      uses: softprops/turnstyle@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0

    - name: Get manifest version
      id: set_version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: './src/ui/Kuriimu2.Cmd/Resources/version.json'
        prop_path: 'version'

    - name: Create manifests
      run: |
        mkdir ./update/Windows
        mkdir ./update/Linux
        mkdir ./update/Mac
        echo '{"source_type": "Github Action", "version": "${{ steps.set_version.outputs.prop }}", "build_number": "${{ github.run_id }}", "application_name": "Kuriimu2.exe" }' > ./update/Windows/manifest.json
        echo '{"source_type": "Github Action", "version": "${{ steps.set_version.outputs.prop }}", "build_number": "${{ github.run_id }}", "application_name": "Kuriimu2" }' > ./update/Linux/manifest.json
        echo '{"source_type": "Github Action", "version": "${{ steps.set_version.outputs.prop }}", "build_number": "${{ github.run_id }}", "application_name": "Kuriimu2" }' > ./update/Mac/manifest.json
        echo '{"source_type": "Github Action", "version": "${{ steps.set_version.outputs.prop }}", "build_number": "${{ github.run_id }}" }' > ./src/ui/Kuriimu2.Cmd/Resources/version.json

    - name: Setup NuGet sources
      run: |
        dotnet nuget update source Kuriimu2 --username ${{ secrets.GITHUB_TOKEN }} --password ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish Kuriimu2 Mac
      run: |
        dotnet publish ./src/ui/Kuriimu2.Cmd/Kuriimu2.Cmd.csproj --configuration Release --framework net8.0 -p:PublishSingleFile=true --runtime osx-x64 --output ./dist/final/Mac
        mv ./dist/final/Mac/Kuriimu2.Cmd ./dist/final/Mac/Kuriimu2
        rm ./dist/final/Mac/*.pdb

    - name: Publish Kuriimu2 Windows
      run: |
        dotnet publish ./src/ui/Kuriimu2.Cmd/Kuriimu2.Cmd.csproj --configuration Release --framework net8.0 -p:PublishSingleFile=true --runtime win-x64 --output ./dist/final/Windows
        mv ./dist/final/Windows/Kuriimu2.Cmd.exe ./dist/final/Windows/Kuriimu2.exe
        rm ./dist/final/Windows/*.pdb

    - name: Publish Kuriimu2 Linux
      run: |
        dotnet publish ./src/ui/Kuriimu2.Cmd/Kuriimu2.Cmd.csproj --configuration Release --framework net8.0 -p:PublishSingleFile=true --runtime linux-x64 --output ./dist/final/Linux
        mv ./dist/final/Linux/Kuriimu2.Cmd ./dist/final/Linux/Kuriimu2
        rm ./dist/final/Linux/*.pdb
        
    - name: Publish plugins
      run: |
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/ArcSystemWorks/ArcSystemWorks.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Atlus/Atlus.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/BandaiNamco/BandaiNamco.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Beeworks/Beeworks.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Capcom/Capcom.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Circus/Circus.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Criware/Criware.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/DotEmu/DotEmu.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/DreamCatcher/DreamCatcher.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Enterbrain/Enterbrain.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Felistella/Felistella.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/FurYu/FurYu.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Gust/Gust.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/HeadstrongGames/HeadstrongGames.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/HuneX/HuneX.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/IntiCreates/IntiCreates.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Kadokawa/Kadokawa.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/KhronosGroup/KhronosGroup.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/KoeiTecmo/KoeiTecmo.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Konami/Konami.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Level5/Level5.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/MercurySteam/MercurySteam.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/MostWantedEntertainment/MostWantedEntertainment.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Nintendo/Nintendo.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/NipponIchiSoftware/NipponIchiSoftware.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/PowerVR/PowerVR.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Primula/Primula.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Sega/Sega.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Shade/Shade.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/Sony/Sony.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/SpikeChunsoft/SpikeChunsoft.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/SquareEnix/SquareEnix.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/StingEntertainment/StingEntertainment.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/SuperflatGames/SuperflatGames.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/TamSoft/TamSoft.sln 
        dotnet build --output ./dist/final/plugins --configuration Release --framework net8.0 ./plugins/VBlankEntertainment/VBlankEntertainment.sln 
        rm ./dist/final/plugins/*.pdb
        rm ./dist/final/plugins/*.deps.json
        
    - name: Copy plugins to Kuriimu2 folder
      run: |
        xcopy /I .\dist\final\plugins .\dist\final\Windows\plugins
        xcopy /I .\dist\final\plugins .\dist\final\Linux\plugins
        xcopy /I .\dist\final\plugins .\dist\final\Mac\plugins
      shell: cmd
      
    - name: Zip Windows release
      uses: papeloto/action-zip@v1
      with:
        files: ./dist/final/Windows
        dest: ./update/Windows/latest.zip
      
    - name: Zip Linux release
      uses: papeloto/action-zip@v1
      with:
        files: ./dist/final/Linux
        dest: ./update/Linux/latest.zip
        
    - name: Zip Mac release
      uses: papeloto/action-zip@v1
      with:
        files: ./dist/final/Mac
        dest: ./update/Mac/latest.zip
      
    - name: Install openSSL
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install openssl.light
      
    - name: Sign release
      run: |
        echo "$PRIVATE_KEY" > privatekey.pem
        openssl dgst -sha512 -sign privatekey.pem -out ./update/Windows/latest.sig ./update/Windows/latest.zip
        openssl dgst -sha512 -sign privatekey.pem -out ./update/Linux/latest.sig ./update/Linux/latest.zip
        openssl dgst -sha512 -sign privatekey.pem -out ./update/Mac/latest.sig ./update/Mac/latest.zip
      shell: bash
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_CMD }}
      
    - name: Clone update repository
      run: |
        git clone https://github.com/FanTranslatorsInternational/Kuriimu2-CommandLine-Update ./update_repo
        git checkout --orphan squash HEAD
        
    - name: Move update files to update repo
      run: |
        mv -Force ./update/Windows/* ./update_repo/Windows
        mv -Force ./update/Linux/* ./update_repo/Linux
        mv -Force ./update/Mac/* ./update_repo/Mac
        
    - name: Commit changes to update repo
      run: |
        cd ./update_repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *
        git commit -m "Update binaries" -a
        
    - name: Push changes to update repo
      run: |
        cd ./update_repo
        git branch -M main
        git remote set-url origin https://oauth2:${{ secrets.PRIVATE_ACCESS_TOKEN }}@github.com/FanTranslatorsInternational/Kuriimu2-CommandLine-Update.git
        git push --force origin main
      
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kuriimu2 Windows
        path: ./dist/final/Windows
        
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kuriimu2 Linux
        path: ./dist/final/Linux
        
    - name: Upload Mac artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kuriimu2 Mac
        path: ./dist/final/Mac
